### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by ptr1226** [reversed2603/gamesense_legacy#3]
![image](https://user-images.githubusercontent.com/114344838/218254869-4340a6b5-1aa7-4aba-929b-6fedacbe17b1.png)

does someone know fix?

**Comment by ptr1226** [comment]
![image](https://user-images.githubusercontent.com/114344838/218254977-7f394c75-d80c-4cff-b40f-9204753cbf88.png)

**Comment by reversed2603** [comment]
use brain next time
